### ISSUE TITLE
HDR+ Bracketing 

### ISSUE THREAD

**Issue by lapkasasha** [martin-marek/hdr-plus-swift#11]
a couple of years ago google added exposure bracketing to google camera, i would like to see it in your app too if possible

**Comment by martin-marek** [comment]
Thanks for the suggestion, @lapkasasha. I'm aware of this and agree it would be nice. The issue is that during alignment, all frames need to have the same exposure. So we would need to have a way to adjust each frame's exposure to match the reference frame. I don't know how easy this is – are all pixel intensities linear?

For know, I recommend that you underexpose the whole burst by the same amount (even though this won't give you the same performance).

If you (or anyone else) wants to implement this, I can try to help.

**Comment by chris-rank** [comment]
I believe that assuming linearity is a very good approximation and should work reasonably well. However, special care has to be taken at the clipping point of the sensor for very bright pixels. My main concern would be that Google uses a very specific bracketing pattern and I think that cameras do not give the user the amount of control to automatically take a burst with such a pattern. 

https://ai.googleblog.com/2021/04/hdr-with-bracketing-on-pixel-phones.html

**Comment by lapkasasha** [comment]
Have you thought about writing your own smartphone application with Rav
image capture and your application's algorithms?Or Google will not allow
such an application to appear in the play market?I know that's what Google
Camera is for, but it's officially only on pixels, people would love to see
similar algorithms in their smartphones

вс, 13 нояб. 2022 г., 11:11 Martin Marek ***@***.***>:

**Comment by martin-marek** [comment]
I don't have any plans for a smartphone app. You could theoretically run my align+merge code on an iPhone (since it's written in Metal), but iPhones already have a better pipeline than this. Porting Burst Photo to Android would require a full rewrite.
