### ISSUE TITLE
Download app from Releases not launching

### ISSUE THREAD

**Issue by Blatman** [martin-marek/hdr-plus-swift#3]
Monterey 12.6

The Burst Photo binary in the MacOS folder needs executable permissions - chmod 755 'Burst Photo' will allow the app to launch OK.

**Comment by martin-marek** [comment]
Thanks for pointing this out!

I was able to replicate the issue and fix it (on my computer) by running `chmod +x "Burst Photo.app/Contents/MacOS/Burst Photo"` …but this certainly shouldn't be necessary.

I'll look for a way to fix this. In the meantime, you can also download the app from [App Store](https://apps.apple.com/us/app/burst-photo/id1586020075?mt=12&itsct=apps_box_badge&itscg=30200).

**Comment by martin-marek** [comment]
I (think) I fixed the issue by creating the release zip file using Mac's built-in Archive Utility, rather than relying on GitHub to create the zip file. I found some helpful discussion related to the problem [here](https://forum.xojo.com/t/catalina-unzip-file-permissions-problems/52435/12).

Could you please verify whether the release now works for you?

**Comment by martin-marek** [comment]
Perfect, thanks for confirming!
