### ISSUE TITLE
Compile for OSX 10.x.x

### ISSUE THREAD

**Issue by andreasGothe** [martin-marek/hdr-plus-swift#5]
Is it possible to compile this for OS versions before OSX11 'BigSur' - or is there a reason for this not to work?

**Comment by martin-marek** [comment]
It is currently not possible because of several UI features. I'm not sure which exactly but you could test that yourself if you're really interested (if you fork and run the main branch).

I don't plan on changing this since it would require extra work and possibly increase code complexity.

**Comment by martin-marek** [comment]
I've just added a `cli.swift` file and a new build target that runs this file (without a GUI). You should be able to use it on macOS 10.15 to batch process bursts. Unfortunately, you can only run it from Xcode (rather than Terminal). But I assume you could make it into a Terminal app if you're interested.

**Comment by Alex-Vasile** [comment]
> Thank you ... where is my AppleDeveloperID again? And I guess XCode14 (the one with the simplicity and power of Swift and SwiftUI) needs at least OSX11. But I'm eager to check it out when I find some time - what else can we do on a sunday? :)

If you plan to only run it locally, you can use your appleID instead of needing a full developer account.

**Comment by chris-rank** [comment]
Is this still an issue as the CLI can be used with macOS 10.15?
