### ISSUE TITLE
Seg Fault when merging iPhone 13 ProRaw Files

### ISSUE THREAD

**Issue by Alex-Vasile** [martin-marek/hdr-plus-swift#7]
To test things out I shot some ProRaw files with my iPhone 13 pro. I let it enable it automatic night mode. The resulting raw files (3 of them) that I shot sequentially I transfer to my Mac. When I drag them into Burst Photo the app immediately crashes. If I launch it from the terminal to try to get some better info into what's going on all I am told is "segmentation fault". This is with the version 1.1 (14). The version I have in #6 does not crash.

**Comment by martin-marek** [comment]
Thanks for reporting this. By any chance, did you mean ProRaw (instead of ProRes)? I was able to replicate this with ProRaw on iPhone 13 Pro. The issue is that ProRaw DNG files are already demoisaced but Burst Photo only supports mosaiced raw images.

Version 1.0 was not supposed to work with these images – the output will be unusable. Version 1.1 on the other hand is not supposed to crash. I [fixed](https://github.com/martin-marek/hdr-plus-swift/commit/f0c1b5330318a72a7f0baa5ea605b1d4b38df977) this issue (for now) by printing an error message when ProRaw files are used.

**Comment by Alex-Vasile** [comment]
> Thanks for reporting this. By any chance, did you mean ProRaw (instead of ProRes)? I was able to replicate this with ProRaw on iPhone 13 Pro. The issue is that ProRaw DNG files are already demoisaced but Burst Photo only supports mosaiced raw images.
> 
> 
> 
> Version 1.0 was not supposed to work with these images – the output will be unusable. Version 1.1 on the other hand is not supposed to crash. I [fixed](https://github.com/martin-marek/hdr-plus-swift/commit/f0c1b5330318a72a7f0baa5ea605b1d4b38df977) this issue (for now) by printing an error message when ProRaw files are used.

Yup. ProRaw, my bad. I did mean to talk about still raws, not video.
